-- Importa datos en la tabla EQUIPO
LOAD DATA INFILE 'C:\Users\jessa\Downloads\Escritorio\PROYECT-FUT BD/EQUIPO.CSV'
INTO TABLE EQUIPO
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- Importa datos en la tabla JUGADOR
LOAD DATA INFILE 'C:\Users\jessa\Downloads\Escritorio/JUGADOR.CSV'
INTO TABLE JUGADOR
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- Importa datos en la tabla ENTRENADOR
LOAD DATA INFILE 'C:\Users\jessa\Downloads\Escritorio\PROYECT-FUT BD/ENTRENADOR.CSV'
INTO TABLE ENTRENADOR
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


-- Importa datos en la tabla PARTIDO
LOAD DATA INFILE 'C:\Users\jessa\Downloads\Escritorio\PROYECT-FUT BD/PARTIDO.CSV'
INTO TABLE PARTIDO
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;




-- Importa datos en la tabla CAMPO
LOAD DATA INFILE 'C:\Users\jessa\Downloads\Escritorio/CAMPO.CSV'
INTO TABLE CAMPO
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;





-- Importa datos en la tabla ARBITRO
LOAD DATA INFILE 'C:\Users\jessa\Downloads\Escritorio\PROYECT-FUT BD/ARBITRO.CSV'
INTO TABLE ARBITRO
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;



-- Importa datos en la tabla PARTICIPA
LOAD DATA INFILE 'C:\Users\jessa\Downloads\Escritorio\PROYECT-FUT BD/PARTICIPA.CSV'
INTO TABLE PARTICIPA
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;




-- Importa datos en la tabla DIRIGE
LOAD DATA INFILE 'C:\Users\jessa\Downloads\Escritorio\PROYECT-FUT BD/DIRIGE.CSV'
INTO TABLE DIRIGE
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;



-- Importa datos en la tabla PROGRAMA
LOAD DATA INFILE 'C:\Users\jessa\Downloads\Escritorio\PROYECT-FUT BD/PROGRAMA.CSV'
INTO TABLE PROGRAMA
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


-- Importa datos en la tabla ARBITRAJE
LOAD DATA INFILE 'C:\Users\jessa\Downloads\Escritorio\PROYECT-FUT BD/ARBITRAJE.CSV'
INTO TABLE ARBITRAJE
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;








